version: 2.1

orbs:
  go: gotest/tools@0.0.14

workflows:
  ci:
    jobs:
      - lint
      - go/test:
          name: test-golang-1.17
          executor:
            name: go/golang
            tag:  1.17-alpine
      - go/test:
          name: test-golang-1.18
          executor:
            name: go/golang
            tag:  1.18-alpine
      - go/test:
          name: test-golang-1.19
          executor:
            name: go/golang
            tag:  1.19-alpine
      - go/test:
          name: test-windows
          executor: windows
          pre-steps:
            - run: |
                git config --global core.autocrlf false
                git config --global core.symlinks true
            - run: |
                choco upgrade golang
                echo 'export PATH="$PATH:/c/Program Files/Go/bin"' > $BASH_ENV
            - run: go version

executors:
  windows:
    machine:
      image: windows-server-2019-vs2019:stable
      resource_class: windows.medium
      shell: bash.exe

jobs:

  lint:
    executor:
      name: go/golang
      tag:  1.19-alpine
    steps:
    - checkout
    - go/install-golangci-lint:
        prefix: v1.49.0
        version: 1.49.0
    - go/install: {package: git}
    - run:
        name: Lint
        command: golangci-lint run -v --concurrency 2
